# -*- coding: utf-8 -*-
"""SCT_DS_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4chDDW9G5aC6biCtNrRbblp138h6Vdv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Titanic dataset directly via URL
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Handle missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin', 'PassengerId', 'Name', 'Ticket'], inplace=True, errors='ignore')

print("Data Cleaning Complete! Cleaned Dataset Preview:")
df.head()

# Set up the plotting environment style
sns.set_theme(style="whitegrid")

# Create a multi-plot figure to see all insights at once
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# 1. Survival Distribution
sns.countplot(ax=axes[0, 0], x='Survived', data=df, palette='Set2')
axes[0, 0].set_title('Distribution of Survival (0 = No, 1 = Yes)')

# 2. Survival by Gender
sns.countplot(ax=axes[0, 1], x='Survived', hue='Sex', data=df, palette='Pastel1')
axes[0, 1].set_title('Survival Count by Gender')

# 3. Survival Rate by Passenger Class
sns.barplot(ax=axes[1, 0], x='Pclass', y='Survived', data=df, palette='autumn', errorbar=None)
axes[1, 0].set_title('Survival Rate by Passenger Class')

# 4. Age Distribution
sns.kdeplot(ax=axes[1, 1], data=df, x='Age', hue='Survived', fill=True, palette='coolwarm', common_norm=False)
axes[1, 1].set_title('Age Distribution by Survival Status')

plt.tight_layout()
plt.show()

# 5. Separate Correlation Heatmap
plt.figure(figsize=(8, 6))
numeric_df = df.select_dtypes(include=[np.number])
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()